In [5]:
from pymatgen.ext.matproj import MPRester
import crystal_toolkit

In [3]:
mpr = MPRester("GVPDJzGk7QCVi80Gnm6QCYrKAlJiTtLf")

In [6]:
mp_id = "mp-4019"
CTO_structure = mpr.get_structure_by_material_id(mp_id)
CTO_structure

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

c:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\site-packages\crystal_toolkit\core\jupyter.py:57: UserWarning:

Port {port} not available, using {free_port} instead.



In [7]:
print(CTO_structure)

Full Formula (Ca4 Ti4 O12)
Reduced Formula: CaTiO3
abc   :   5.372049   5.462796   7.636360
angles:  90.000000  90.000000  90.000000
pbc   :       True       True       True
Sites (20)
  #  SP           a         b          c    magmom
---  ----  --------  --------  ---------  --------
  0  Ca    0.509067  0.542398   0.75             0
  1  Ca    0.490933  0.457602   0.25             0
  2  Ca    0.990933  0.042398   0.75             0
  3  Ca    0.009067  0.957602   0.25             0
  4  Ti    0         0.5        0.5             -0
  5  Ti    0         0.5       -0               -0
  6  Ti    0.5       0          0.5             -0
  7  Ti    0.5       0         -0               -0
  8  O     0.076781  0.481328   0.75             0
  9  O     0.923219  0.518672   0.25             0
 10  O     0.423219  0.981328   0.75             0
 11  O     0.576781  0.018672   0.25             0
 12  O     0.790294  0.789614   0.959841        -0
 13  O     0.209706  0.210386   0.459841        -0

In [8]:
print(CTO_structure.composition)

Ca4 Ti4 O12


In [9]:
print(CTO_structure.frac_coords)

[[ 0.50906691  0.54239755  0.75      ]
 [ 0.49093309  0.45760245  0.25      ]
 [ 0.99093309  0.04239755  0.75      ]
 [ 0.00906691  0.95760245  0.25      ]
 [ 0.          0.5         0.5       ]
 [ 0.          0.5        -0.        ]
 [ 0.5         0.          0.5       ]
 [ 0.5         0.         -0.        ]
 [ 0.07678111  0.48132762  0.75      ]
 [ 0.92321889  0.51867238  0.25      ]
 [ 0.42321889  0.98132762  0.75      ]
 [ 0.57678111  0.01867238  0.25      ]
 [ 0.79029372  0.78961378  0.95984128]
 [ 0.20970628  0.21038622  0.45984128]
 [ 0.20970628  0.21038622  0.04015872]
 [ 0.79029372  0.78961378  0.54015872]
 [ 0.70970628  0.28961378  0.95984128]
 [ 0.29029372  0.71038622  0.45984128]
 [ 0.29029372  0.71038622  0.04015872]
 [ 0.70970628  0.28961378  0.54015872]]


In [11]:
from pymatgen.transformations.advanced_transformations import SlabTransformation
import numpy as np

miller_index = [0, 0, 1]
slab_size = np.linspace(1, 10, 10)
vacuum_size = np.linspace(1, 15, 10)

min_slab_size = 10 # Thickness of the slab
min_vacuum_size = 15 # Thickness of the vacuum layer

slab_transformation = SlabTransformation(
    miller_index=miller_index,
    min_slab_size=min_slab_size,
    min_vacuum_size=min_vacuum_size,
    lll_reduce=True, # Makes the slab more orthogonal
    center_slab=True, # Centers the slab w/ vacuum on top and bottom
    in_unit_planes=True # Slab thickness specified as number of planes, not Angstroms
)

cto_001 = slab_transformation.apply_transformation(CTO_structure)
cto_001


c:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\site-packages\crystal_toolkit\core\jupyter.py:57: UserWarning:

Port {port} not available, using {free_port} instead.



c:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymatgen\analysis\local_env.py:4019: UserWarning:

No oxidation states specified on sites! For better results, set the site oxidation states in the structure.

c:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymatgen\analysis\local_env.py:4021: UserWarning:

No oxidation states specified on sites! For better results, set the site oxidation states in the structure.

c:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymatgen\analysis\local_env.py:3933: UserWarning:

CrystalNN: cannot locate an appropriate radius, covalent or atomic radii will be used, this can lead to non-optimal results.

c:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymatgen\analysis\local_env.py:4019: UserWarning:

No oxidation states specified on sites! For better results, set the site oxidation states in the structure.

c:\Users\ryana\AppData\Local\Programs\Python\Python